### ISSUE TITLE
Link to Pull Request shown for workflow runs not associated with a PR

### ISSUE THREAD

**Issue by stianst** [catchpoint/foresight-issues#2]
Looks like "Pull Request" link at the top of a workflow run points to a PR when it is not a PR, but is empty when it is a PR.

Example from a "pull_request" workflow run:

![image](https://user-images.githubusercontent.com/2271511/194553278-9d4e2f03-7400-4c82-80a0-9b3b0b6ece40.png)

Example from a "schedule" workflow run:

![image](https://user-images.githubusercontent.com/2271511/194553224-e6e1f078-47d1-437b-a8bf-de3c0420592e.png)

This is also reflected in the workflow runs list:

![image](https://user-images.githubusercontent.com/2271511/194553150-78388d56-38f5-47ce-b49a-0f19738ab61f.png)

"Keycloak 19 cannot register" is a schedule event, but looks like a PR in the workflow runs list, while "skip assert if key format not raw" is a pull_request event doesn't have the PR icon.

**Comment by burakkantarci** [comment]
We've found the reason behind this issue. We are developing a solution for that!
