### ISSUE TITLE
Ability to configure workflows for a repository

### ISSUE THREAD

**Issue by stianst** [catchpoint/foresight-issues#7]
It would be great to be able to configure what workflows are enabled in Foresight. 

We for example have a (weird) workflow that triggers on commits, and you can imagine how much noise that creates in the Foresight UI.

![image](https://user-images.githubusercontent.com/2271511/194556198-a1db78b2-f878-4ff3-a173-2cda80ee3730.png)

**Comment by burakkantarci** [comment]
We are going to add a panel for configuring workflows

![Screenshot 2022-11-16 at 16 17 44](https://user-images.githubusercontent.com/5147390/202190882-b435bb8a-3047-4d13-a23b-3c5c2a00aca4.png)

**Comment by burakkantarci** [comment]
You can watch / unwatch your workflows from here: [https://app.runforesight.com/organization/workflows](https://app.runforesight.com/organization/workflows)

**Comment by stianst** [comment]
@burakkantarci on the watch/unwatch page I'm only seeing some of our workflows, which means I can't unwatch all that I want. For example we have a workflow "Keycloak GitHub Bot" that I'd like to unwatch, but it's not on the list on https://app.runforesight.com/organization/workflows.

**Comment by burakkantarci** [comment]
@stianst could you send a screenshot of the page?

**Comment by stianst** [comment]
![image](https://user-images.githubusercontent.com/2271511/210756941-6efa5a30-e7ad-49c9-b6e1-fb9ba33613e4.png)

**Comment by burakkantarci** [comment]
@suleymanbarman can you look at the issue?

**Comment by stianst** [comment]
FIY here's our current workflows:

![image](https://user-images.githubusercontent.com/2271511/210786567-b3032712-2dc5-4ccf-8359-c3db806eeb83.png)

Note: "CodeQL Java|JS Adapter|Themes" have been removed, so these are just old results from GitHub

**Comment by burakkantarci** [comment]
We released a fix; thanks @stianst Could you please check if that works?

**Comment by stianst** [comment]
@burakkantarci yup, works great now. Thanks :)
