### ISSUE TITLE
Link to workflow/test results for a PR

### ISSUE THREAD

**Issue by stianst** [catchpoint/foresight-issues#8]
It would be great to have a link to the workflow and test results for a PR, so both contributors and maintainers can quickly look at the results.

I'm not sure what the best way is to do this, one way could be to add a comment to the PR, but that could be a bit noisy as it mixes with humans talking and also generates extra notifications for PRs.

**Comment by suleymanbarman** [comment]
A couple of capabilities were added to Foresight which are listed below:
1. Enable/Disable pr-comment and check-run on Foresight
<img width="584" alt="image" src="https://user-images.githubusercontent.com/3482186/206684189-0e2a7b54-c9cf-4431-9079-d7826c8f088b.png">

2. Contributors can see the summary of PR and can access related Foresight by clicking badges
<img width="944" alt="image" src="https://user-images.githubusercontent.com/3482186/206684537-7524d630-c51e-4ed3-8f59-466955b69ec1.png">

3. Check-run results can be followed 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/3482186/206684656-dd29e136-f68f-4e64-8070-63968a91df04.png">

4. Contributoes can see check-run in details
<img width="882" alt="image" src="https://user-images.githubusercontent.com/3482186/206685032-40dc2a72-c026-4b37-804e-269618c195e2.png">
